### ISSUE TITLE
how to add it to transformers‘s mdoel??

### ISSUE THREAD

**Issue by Dhaizei** [neelsjain/NEFTune#11]
such as 

    trainer = Trainer(
        model=model, tokenizer=tokenizer, args=training_args, **data_module
    )

how to add it?

**Comment by Dhaizei** [comment]
model.base_model.model.model.embed_tokens.forward = noised_embed(model.base_model.model.model.embed_tokens, noise_alpha)
 ---->
model.base_model.embed_tokens.forward = noised_embed(model.base_model.embed_tokens, noise_alpha)

maybe better

**Comment by YuxinWenRick** [comment]
Hi, did you still encounter the issue after modifying the code? If not, you might want to check out [SFTTrainer](https://huggingface.co/docs/trl/main/en/sft_trainer#enhance-models-performances-using-neftune). They've made NEFTune user-friendly.

Let us know if you have any further questions!
