### ISSUE TITLE
how to add multi-turns function?

### ISSUE THREAD

**Issue by Dhaizei** [neelsjain/NEFTune#14]
How to turn it into a fine-tuning of multi-turns dialogue, and does this trick also help multi-turns dialogue?

**Comment by neelsjain** [comment]
We did not test NEFTune on multi-turn dialogue (so unclear), and I think you can adopt this repository by making changes in `dataset.py` folder. Alternatively, I think NEFTune is now integrated into Trainer in HF, so it should be easy to call there.
