### ISSUE TITLE
quesiton about the noise injection location

### ISSUE THREAD

**Issue by zhhao1** [neelsjain/NEFTune#15]
Thank for you interesting work. In Algorithm 1, it seems that noise is injected into the embedding of the instruction X. However, the [code](https://github.com/neelsjain/NEFTune#code) example  shows that the noise is injected into the embedding of the instruction + answer. Is there some inconsistency here?

**Comment by neelsjain** [comment]
Good question. This a slight artifact of how instruction finetuning is set up. Y is actually a subset of X, so it is injected into both.
