### ISSUE TITLE
RuntimeError: ``sharded_state_dict`` can only be used when parameters are flatten and sharded.

### ISSUE THREAD

**Issue by Sniper970119** [neelsjain/NEFTune#2]
Hello ,could you ask me a favor? I have some problem with this code,
I first run `convert_hf_to_fsdp.py`  

```
HF_CHECKPOINT_PATH=/......./llama2-7b-hf
SAVE_PATH=/......./NEFTune/test_7b/

python convert_hf_to_fsdp.py --load_path $HF_CHECKPOINT_PATH --save_path $SAVE_PATH #--add tokens $NUM_TOKENS
```

and get the files `.metadata` and `__0_0.distcp` under the file test_7b

then I run the `train.py' with config 

```
--init_checkpoint_path /......./NEFTune/test_7b 
--model_config_path /......../llama2-7b-hf 
--wrapped_class_name LlamaDecoderLayer 
--data_path datasets/alpaca-train.jsonl 
--added_tokens 0 
--act_checkpointing 
--lr 5e-5 
--accumulation_steps 8 
--batch_size 1 
--checkpoint_path ./checkpoints/naive 
--neftune_alpha 5
```
just remove wandb config the change the path

I got a error 
`RuntimeError: ``sharded_state_dict`` can only be used when parameters are flatten and sharded.`
Can you help me see why？

**Comment by Sniper970119** [comment]
I already run the command `pip install -r requirement.txt'
but because `pytorch` is a bit big ,so I use a higher version.

```
--extra-index-url https://download.pytorch.org/whl/cu118
torch>=2.0.1+cu118
torchvision>=0.15.2+cu118
torchaudio 
datasets==2.12.0
transformers==4.30.1
sentencepiece==0.1.99
protobuf==3.20.0
accelerate==0.20.3
shortuuid
wandb
lion-pytorch
```

**Comment by neelsjain** [comment]
Hey! I think you might want to try seeing if you can convert back to an HF model. This will let us whether (1) something happened during the conversion (2) something is wrong with train.py.

Additionally, I would suggest downgrading the torch package to 2.0.1. Pytorch made some changes to FSDP on the latest version (but I don't think this is why you having the current problem).

**Comment by Sniper970119** [comment]
Hi。I tried `convert_fsdp_to_hf .py`   it run without error.
It seem like something wrong in `train.py`

**Comment by Sniper970119** [comment]
<img width="1396" alt="image" src="https://github.com/neelsjain/NEFTune/assets/30463691/e269806f-84ff-4b32-b5c3-5defe7ea7ea7">
I just run code to find which line get the error, I have another error , emm

**Comment by neelsjain** [comment]
This error is due to the pytorch to 2.0.1 (double check with the requirements) version just downgrade. Pytorch made changes in FSDP.

**Comment by Sniper970119** [comment]
> This error is due to the pytorch to 2.0.1 (double check with the requirements) version just downgrade. Pytorch made changes in FSDP.

tks, I will try 2.0.1 version

**Comment by Sniper970119** [comment]
but  it still have this problem

<img width="1418" alt="image" src="https://github.com/neelsjain/NEFTune/assets/30463691/2e2a0eed-3e26-4f2f-b605-4397866d270c">
<img width="858" alt="image" src="https://github.com/neelsjain/NEFTune/assets/30463691/4040806a-7ca4-485a-9bd4-e22e2605ac33">

**Comment by neelsjain** [comment]
@Sniper970119, did that work for you? 

I am going to close this issue but feel free to open it again.
