### ISSUE TITLE
QLoRA implementation

### ISSUE THREAD

**Issue by marianbastiUNRN** [neelsjain/NEFTune#3]
Hi there, congrats on this interesting work!

On the paper you share results for QLoRA training, yielding good results. 
This seems to be omitted in the code implementation so, where should one begin to experiment training adapters with this technique?

**Comment by neelsjain** [comment]
We used the original implementation: https://github.com/artidoro/qlora, and rewrote the forward similar to what is in the README.md right after this line: https://github.com/Ping-C/qlora/blob/90e5abc8ac4c3ad6ad6529b1ce3e4d0dbdd7765e/qlora.py#L708.

A note on the QLORA repository. When using it initially I had issues setting up the dependencies. I found that I needed to download cudatoolkit package and manually rewrite the cuda cpu file in bitsandbytes to the corresponding gpu one. Very similar to these issues: https://github.com/search?q=repo%3ATimDettmers%2Fbitsandbytes+CUDA+Setup+failed+despite+GPU+being+available.&type=issues&p=2. 

Let me know if you have any additional problems.
