### ISSUE TITLE
More benchmarks

### ISSUE THREAD

**Issue by eyuansu62** [neelsjain/NEFTune#6]
Do you guys test your model on classical benchmarks such as MMLU, GSM8K, HumanEVAL?
Perhaps the relative improvement on AlpacaEval is merely due to GPT-4's preference for longer responses.

**Comment by neelsjain** [comment]
Please see our paper: https://arxiv.org/abs/2310.05914. We explored OpenLLM Leaderboard tasks and saw no improvement. We did a small human evaluation on one of our models and explicitly discussed the length factor in the Analysis section.
