### ISSUE TITLE
Question about output embedding from noised tokens

### ISSUE THREAD

**Issue by isamu-isozaki** [neelsjain/NEFTune#7]
Hi! Thanks for the very interesting paper! We were discussing this paper in the hugging face reading group and we wondered, for the new model trained with noise token embeddings, do the output embeddings have larger cone/lower cosine similarities/different singular values compared to the original model? (For output embeddings, not the token embeddings)

We thought larger cones led to less overfitting intuitively. Anyway, thanks for the paper again!

**Comment by isamu-isozaki** [comment]
Oh, does having similar singular values just mean the cones are similar too?

**Comment by neelsjain** [comment]
I don't think I quite understand your question, but we found similar singular values. When plotting TSNE plot of a subset of the vocabulary, we found the embedding spaces were similar. Additionally, we found that if you freeze the embedding and train the rest of the most you still see performance increases.

Closing this issue but feel free to open it again.
